model_params:
  name: 'VanillaVAE'
  in_channels: 3
  latent_dim: 128


data_params:
  data_path: "data/chest_xray/sep_train_test/"
  train_batch_size: 16
  val_batch_size: 4
  patch_size: 64
  num_workers: 4


exp_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.0025
  manual_seed: 1265
  leaky_relu_weight: 0.01

trainer_params:
  gpus: [0]
  max_epochs: 50

logging_params:
  save_dir: "logs/chest_xray/sep_train_test/"
  name: "VanillaVAE"
 